parameters:
  locale: 'en'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\EventListener\Image:
    tags:
      - { name: kernel.event_listener, event: image.created }

  app.cache.memcached:
    class: \Memcached
    factory: ['Symfony\Component\Cache\Adapter\MemcachedAdapter', 'createConnection']
    arguments: ['%env(MEMCACHED_SERVER_DSN)%']

  app.cache.memcached_adapter:
    class: Symfony\Component\Cache\Adapter\MemcachedAdapter
    arguments:
      - '@app.cache.memcached'
      - ''
      - 3600

  Psr\Cache\CacheItemPoolInterface:
    alias: app.cache.memcached_adapter